# Envio da proposta
POST http://127.0.0.1:8080/proposta HTTP/1.1
content-type: application/json

{
  "nome": "João",
  "sobrenome": "Silva",
  "cpf": "123.456.789-00",
  "telefone": "(31) 99999-8888",
  "renda": 3500.50,
  "valorSolicitado": 10000.00,
  "prazoPagamento": 24
}
